### ISSUE TITLE
update wget version in base busybox image to include the --recursive option 

### ISSUE THREAD

**Issue by fubar2** [BioContainers/multi-package-containers#1676]
When a biocontainer with planemo tries to build a new biocontainer locally, it fails because wget is called with a missing recursive option. This is an edge case that took some doing to induce, but it will appear the next time someone tries `wget --recursive` even for a reasonable reason inside a biocontainer.

Galaxy log causing this shows it's trying to build the planemo/galaxyxml/git container - which is running at the time.

```
galaxy.tool_util.deps.containers INFO 2021-04-25 12:06:18,995 [pN:main.web.1,p:3729443,w:1,m:0,tN:LocalRunner.work_thread-0] Checking with container resolver [ExplicitContainerResolver[]] found description [None]
fi
  docker kill 38f0771b56c143b9a69d89f5bfa29769 &> /dev/null
}
trap _on_exit 0
docker inspect quay.io/biocontainers/mulled-v2-c0c9dd2959e833cf8c69ae23a9398ddb0db5c98f:5d3a99482f42f5e17ec122729f67bf7be64df9e9-0 > /dev/null 2>&1
[ $? -ne 0 ] && docker pull quay.io/biocontainers/mulled-v2-c0c9dd2959e833cf8c69ae23a9398ddb0db5c98f:5d3a99482f42f5e17ec122729f67bf7be64df9e9-0 > /dev/null 2>&1

```

This in the tool log:

```
stdout:wget -q --recursive -O /home/ross/.planemo/involucro https://github.com/involucro/involucro/releases/download/v1.1.2/involucro
stderr:wget: unrecognized option '--recursive'
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

Usage: wget [-c|--continue] [-s|--spider] [-q|--quiet] [-O|--output-document FILE]
	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
	[-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	-s	Spider mode - only check file existence
	-c	Continue retrieval of aborted transfer
	-q	Quiet
	-P DIR	Save to DIR (default .)
	-T SEC	Network read timeout is SEC seconds
	-O FILE	Save to FILE ('-' for stdout)
	-U STR	Use STR for User-Agent header
	-Y	Use proxy ('on' or 'off')

galaxy.tool_util.deps.installable WARNING: Involucro installation requested and failed.
Traceback (most recent call last):
  File "/usr/local/bin/planemo", line 10, in <module>
    sys.exit(planemo())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/planemo/commands/cmd_test.py", line 82, in cli
    return_value = test_runnables(ctx, runnables, original_paths=uris, **kwds)
  File "/usr/local/lib/python3.8/site-packages/planemo/engine/test.py", line 34, in test_runnables
    with galaxy_config(ctx, runnables, **kwds) as config:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 218, in galaxy_config
    with c(ctx, runnables, **kwds) as config:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 477, in local_galaxy_config
    _handle_container_resolution(ctx, kwds, properties)
  File "/usr/local/lib/python3.8/site-packages/planemo/galaxy/config.py", line 1342, in _handle_container_resolution
    involucro_context = build_involucro_context(ctx, **kwds)
  File "/usr/local/lib/python3.8/site-packages/planemo/mulled.py", line 40, in build_involucro_context
    raise Exception("Failed to install involucro for Planemo.")
Exception: Failed to install involucro for Planemo.

```

**Comment by bgruening** [comment]
Is this than building a container inside a container? You can also depend on wget and include it in the container.

**Comment by fubar2** [comment]
Ah - yes, that would work - thanks!
I don't need to go there any more - decided to stop diving down that particular rabbit hole.
